name: music-assistant-server
title: Music Assistant (server)
base: core24
version: '2.2.1' 
license: Apache-2.0
summary: Free and opensource Media library manager
description: |
  Music Assistant is a free, opensource Media library manager that connects to your 
  streaming services and a wide range of connected speakers. The server is the beating 
  heart, the core of Music Assistant and must run on an always-on device like a 
  Raspberry Pi, a NAS or an Intel NUC or alike. 
  
  This project is not related to the official project, nor endorsed by it. 
website: https://music-assistant.io/
donation: https://paypal.me/giaeveronline
source-code: https://github.com/giaever-online-iot/music-assistant-server
issues:
  - https://github.com/giaever-online-iot/music-assistant-server/issues
  - https://github.com/music-assistant/hass-music-assistant/issues
grade: stable
confinement: strict

platforms:
  amd64: {}
  arm64: {}

apps:
  music-assistant:
    command: ./bin/mass --config $SNAP_DATA --log-level debug
    daemon: simple
    restart-condition: always
    environment:
      PIP_USER: 1
      PIP_ROOT_USER_ACTION: ignore
    plugs:
      - network
      - network-bind
    command-chain:
      - bin/snapcraft-preload
      - cmd-chain/env-wrapper

package-repositories:
  - type: apt
    url: https://www.deb-multimedia.org
    suites: [unstable]
    components: [main]
    key-id: A401FF99368FA1F98152DE755C808C2B65558117
    priority: defer
  # - type: apt
  #   ppa: deadsnakes/ppa
  #   priority: always

parts:
  snapcraft-preload:
   source: https://github.com/sergiusens/snapcraft-preload.git
   plugin: cmake
   cmake-parameters:
     - -DCMAKE_INSTALL_PREFIX=/
   build-packages:
     - on amd64:
       - gcc-multilib
       - g++-multilib
        
  music-assistant:
    plugin: python
    source: https://github.com/music-assistant/server.git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    python-requirements:  [requirements_all.txt]
    # build-environment:
    #   - PARTS_PYTHON_INTERPRETER: "python3.12"
    python-packages:
      - setuptools
      - wheel
      - Cython
      - pip
      - build
    build-packages:
      - autoconf
      - build-essential
      - cmake
      - cython3
      - pkg-config
      # - python3.12-dev
      - libglu1-mesa-dev
      - libsox-fmt-all
      - libsox3
      - freeglut3-dev
      - sox
      - cifs-utils
      - libnfs-utils
    stage-packages:
      - deb-multimedia-keyring
      # - python3.12-venv
      - snapserver
      - ffmpeg
      - libglu1-mesa
      - libglut3.12
      - libopengl0
      - libpulse0
    stage:
      - '*'
      # - -lib/python3.12/site-packages/music_assistant/server/providers/spotify/bin/librespot-*
      # - -lib/python3.12/site-packages/music_assistant/server/providers/spotify/bin/librespot-linux-arm
    # override-stage: |
    #   craftctl default 
    #   find "${CRAFT_STAGE}/bin" -type f -executable -exec sed -i 's/!\/usr\/bin\/env python3.12/!\/usr\/bin\/env python3/' {} \;
    #   sed -i 's/include-system-site-packages = false/include-system-site-packages = true/g' "${CRAFT_STAGE}/pyvenv.cfg"

  cmd:
    plugin: dump
    source: ./src
    source-type: local
    organize:
      'env-wrapper': cmd-chain/env-wrapper